### ISSUE TITLE
Didn’t receive data from facebook lead form 

### ISSUE THREAD

**Issue by Aompos** [fbsamples/lead-ads-webhook-sample#1]
I test Facebook Lead Ad Forms, status it succeeded. But the post api doesn't get any data. Do you know what to do?
Please help me thx

**Comment by MFranca** [comment]
Hey, @Aompos, it looks like you're not getting a notification whenever a new lead has been acquired, right?
I would strongly recommend you make use of the Lead Ads Testing Tool. These are my suggestions:
1) Take a look at the documentation inside the "docs" [folder](https://github.com/fbsamples/lead-ads-webhook-sample/tree/main/docs) in this repository.
2) Leverage the Lead Ads Testing [tool](https://developers.facebook.com/tools/lead-ads-testing) for creating a "dummy lead" and making sure your webservice is being called.
3) You can also make use of the Postman [collection](https://github.com/fbsamples/lead-ads-webhook-sample/blob/main/postman/FB%20Lead%20Ads%20(Part%201%20-%20The%20Webhook).postman_collection.json) "FB Lead Ads (Part 1 - The Webhook)" and the "3 - TEST Lead Generation Notification" example to make sure everything is fine at your side.
I hope all that helps... And since there is no problem regarding the accelerator/sample itself, I'm closing this issue.
Thanks,
França.

**Comment by Aompos** [comment]
@MFranca 
I get page specific information but no lead form data,
Is it relevant to verify the business? pages_manage_metadata,leads_retrieval  permission

**Comment by MFranca** [comment]
@Aompos , are you sure you're calling the right endpoint?
To retrieve the lead data, you should call `https://graph.facebook.com/v{{api version}}/{{leadgen id}}`
You can use either a "user-expiring token" or a "non-expiring token" - you have both examples in the Postman collection provided with the samples. Also, make sure you have the right permissions!
